services:
  - type: web
    env: static
    name: zap-frontend
    rootDir: packages/web
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          name: zap-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: REACT_APP_BASE_URL
        fromService:
          name: zap-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: REACT_APP_NOTIFICATIONS_URL
        fromService:
        value: https://notifications.automatisch.io
  - type: web
    name: zap-backend
    env: node
    plan: free
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm start
    rootDir: packages/backend
    envVars:
      - key: WEB_APP_URL
        fromService:
          name: zap-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEBHOOK_URL
        fromService:
          name: zap-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: POSTGRES_HOST
        fromDatabase:
          name: zap-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: zap-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: zap-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: zap-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: zap-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zap-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zap-redis
          property: port
      - fromGroup: common-env-vars
  - type: worker
    name: zap-worker
    env: node
    plan: starter
    region: singapore
    buildCommand: npm ci && npm run build
    startCommand: npm run start:worker
    rootDir: packages/backend
    envVars:
      - key: WEB_APP_URL
        fromService:
          name: zap-frontend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEBHOOK_URL
        fromService:
          name: zap-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: POSTGRES_HOST
        fromDatabase:
          name: zap-database
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: zap-database
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: zap-database
          property: database
      - key: POSTGRES_USERNAME
        fromDatabase:
          name: zap-database
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: zap-database
          property: password
      - key: REDIS_HOST
        fromService:
          type: redis
          name: zap-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: zap-redis
          property: port
      - fromGroup: common-env-vars
  - type: redis
    name: zap-redis
    region: singapore
    plan: free
    ipAllowList: [] # allow only internal connections
    maxmemoryPolicy: noeviction
databases:
  - name: zap-database
    databaseName: zap
    plan: free
    region: singapore
    postgresMajorVersion: 15

envVarGroups:
  - name: common-env-vars
    envVars:
      - key: APP_ENV
        value: production
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: WEBHOOK_SECRET_KEY
        generateValue: true
      - key: APP_SECRET_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 18.13.0
      - key: SERVE_WEB_APP_SEPARATELY
        value: true
